# Generated by Django 2.2.3 on 2019-07-12 07:26

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='sensitive_data',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50)),
        ),
    ]
